version: '3'
services:

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: mosa-python
    command: pipenv run uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./python:/app
    ports:
      - '8080:8080'
    tty: true

  go:
    build:
      context: ./go
      dockerfile: Dockerfile
    command: go run main.go
    volumes:
      - ./go:/app

  rust:
    build:
      context: ./rust
      dockerfile: Dockerfile
    command: cargo run
    volumes:
      - ./rust:/app

  ts:
    build:
      context: ./typescript
    container_name: mosa-ts
    volumes:
      - ./typescript:/opt/typescript
    command: npm run dev
    ports:
      - "3000:3000"

  ruby:
    build:
      context: ./ruby
      dockerfile: Dockerfile
    container_name: mosa-ruby
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    ports:
      - 8080:8080
    volumes:
      - ./ruby:/app

  cpp:
    build:
      context: ./cpp
      dockerfile: Dockerfile
    container_name: mosa-cpp
    volumes:
      - ./cpp:/app
    ports:
      - 8000:8000
    command: bash -c "cd /app/myapp/build && ./myapp"

  cs:
    build:
      context: ./cs
    container_name: mosa-cs
    volumes:
      - ./cs:/opt/cs
    ports:
      - 8080:8080

  r:
    build:
      context: ./R
      dockerfile: Dockerfile
    volumes:
      - ./R:/app
    command: Rscript ./script.R

  java:
    build:
      context: ./java
    container_name: mosa-java
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./java:/opt/java


  dart:
    build:
      context: ./dart
    container_name: mosa-dart
    ports:
      - 8080:8080
    volumes:
      - ./dart:/opt/dart

  elixir:
    build:
        context: ./elixir
        dockerfile: Dockerfile
    container_name: mosa-elixir
    ports:
      - '8080:8080'
    command: mix phx.server
    tty: true
    environment:
      - MIX_ENV=dev
      - PORT=8080
    volumes:
      - ../:/app
    working_dir: /app/src

  php:
    build:
        context: ./php
        dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html